version: "3"
services:
  frontend:
    container_name: breezer-frontend
    hostname: frontend
    image: breezer-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: # -> используются во время yarn build
        NEXT_PUBLIC_MAIL_ADDRESS: ${NEXT_PUBLIC_MAIL_ADDRESS}
        NEXT_PUBLIC_MAIL_RECIPIENTS: ${NEXT_PUBLIC_MAIL_RECIPIENTS}
        NEXT_PUBLIC_TELEPHONE: ${NEXT_PUBLIC_TELEPHONE}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    env_file: .env # подтягиваем .env целиком
    environment: # -> видны в рантайме процесса Node
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      # Дублируем и публичные, чтобы они были видны и в рантайме:
      NEXT_PUBLIC_MAIL_ADDRESS: ${NEXT_PUBLIC_MAIL_ADDRESS}
      NEXT_PUBLIC_MAIL_RECIPIENTS: ${NEXT_PUBLIC_MAIL_RECIPIENTS}
      NEXT_PUBLIC_TELEPHONE: ${NEXT_PUBLIC_TELEPHONE}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
