version: '3'
services:
  frontend:
    hostname: frontend
    image: breezer-frontend:latest
    container_name: breezer-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USER=${MAIL_USER}
      - NEXT_PUBLIC_MAIL_ADDRESS=${NEXT_PUBLIC_MAIL_ADDRESS}
      - NEXT_PUBLIC_MAIL_RECIPIENTS=${NEXT_PUBLIC_MAIL_RECIPIENTS}
