version: '3'
services:
  frontend:
    container_name: breezer-frontend
    hostname: frontend
    image: breezer-frontend:latest
    env_file: .env # подтягиваем .env целиком
    environment: # -> видны в рантайме процесса Node
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: '1'
    ports:
      - '3000:3000'
    restart: unless-stopped
