import { Product } from "@/entities";
import { ProductShort } from "@/entities/Product";

export const mockProducts: Product[] = [
  // https://fresh-air.moscow/product/brizer-tion-tion-bio-x-base/
  {
    id: "brizer-tion-tion-bio-x-base",
    modelNameEn: "Tion BIO X Base",
    modelNameRu: "Бризер Тион БИО Икс Бэйс",
    inStock: true,
    price: "57 100 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/46/27/2746/images/8199/8199.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/46/27/2746/images/8199/8199.750x350.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Bio X Standard", "Bio X SM Base", "Bio X SM Standard"],
      dimensionsMm: "600х352х183",
      airflowM3h: [30, 45, 60, 75, 90, 125, 160],
      noiseLevelDb: {
        min: 19,
        max: 50,
      },
      modes: ["Приток", "Рециркуляция", "Клапан (до 0 градусов)"],
      features: "Интегрируются в систему «умного дома» Smart Life",
      filterClasses: ["G4", "E11"],
      hiddenWiring: true,
      speeds: 7,
      warrantyDeviceYears: 2,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 40,
      bodyMaterial: "Пластик",
      weightKg: 7,
      nightMode: true,
      airflowMaxM3h: 160,
      roomAreaMaxM2: 50,
      roomAreaRecM2: 40,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1200,
      fanPowerW: 60,
      energyYearWarmKwh: 525,
      energyYearColdKwh: 5300,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 132,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение TION Smart"],
      controlOnDevice: false,
      wifi: true,
      remoteControl: true,
      clusterControl: false,
      recirculation: true,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: false,
        co: false,
        airQuality: true,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "E11",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: false,
      placement: "Внутреннее",
      outdoorTempRange: "−40..+50",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-tion-bio-x-standard/
  {
    id: "brizer-tion-tion-bio-x-standard",
    modelNameEn: "Tion BIO X Standard",
    modelNameRu: "Бризер Тион БИО Икс Стандарт",
    inStock: true,
    price: "58 140 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/45/27/2745/images/8194/8194.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/45/27/2745/images/8194/8194.750x350.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Bio X Base", "Bio X SM Base", "Bio X SM Standard"],
      dimensionsMm: "600х352х183",
      airflowM3h: [30, 45, 60, 75, 90, 125, 160],
      noiseLevelDb: {
        min: 19,
        max: 50,
      },
      modes: ["Приток", "Рециркуляция", "Клапан (до 0 градусов)"],
      features: "Интегрируются в систему «умного дома» Smart Life",
      filterClasses: ["G4", "E11+AK"],
      hiddenWiring: true,
      speeds: 7,
      warrantyDeviceYears: 2,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 40,
      bodyMaterial: "Пластик",
      weightKg: 7,
      nightMode: true,
      airflowMaxM3h: 160,
      roomAreaMaxM2: 50,
      roomAreaRecM2: 40,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1200,
      fanPowerW: 60,
      energyYearWarmKwh: 525,
      energyYearColdKwh: 5300,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 132,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение TION Smart"],
      controlOnDevice: false,
      wifi: true,
      remoteControl: true,
      clusterControl: false,
      recirculation: true,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: false,
        co: false,
        airQuality: true,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "E11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "−40..+50",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-tion-bio-x-sm-standard/
  {
    id: "brizer-tion-tion-bio-x-sm-standard",
    modelNameEn: "Tion BIO X SM Standard",
    modelNameRu: "Бризер Тион БИО Икс эСэМ Стандарт",
    inStock: true,
    price: "76 350 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/43/27/2743/images/8177/8177.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/43/27/2743/images/8177/8177.750x350.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Bio X Base", "Bio X SM Base", "Bio X Standard"],
      dimensionsMm: "600х352х183",
      airflowM3h: [30, 45, 60, 75, 90, 125, 160],
      noiseLevelDb: {
        min: 19,
        max: 50,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      features: "Интегрируются в систему «умного дома» Smart Life",
      filterClasses: ["G4", "E11+AK"],
      hiddenWiring: true,
      speeds: 7,
      warrantyDeviceYears: 2,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 40,
      bodyMaterial: "Пластик",
      weightKg: 7,
      nightMode: true,
      airflowMaxM3h: 160,
      roomAreaMaxM2: 50,
      roomAreaRecM2: 40,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1200,
      fanPowerW: 60,
      energyYearWarmKwh: 525,
      energyYearColdKwh: 5300,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 132,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение TION Smart"],
      controlOnDevice: true,
      wifi: true,
      remoteControl: true,
      clusterControl: false,
      recirculation: true,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: true,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "E11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "−40..+50",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-tion-bio-x-sm-base/
  {
    id: "brizer-tion-tion-bio-x-sm-base",
    modelNameEn: "Tion BIO X SM Base",
    modelNameRu: "Бризер Тион БИО Икс эСэМ Бэйс",
    inStock: true,
    price: "75 200 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/44/27/2744/images/8192/8192.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/44/27/2744/images/8192/8192.750x350.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Bio X Base", "Bio X SM Standard"],
      dimensionsMm: "600х352х183",
      airflowM3h: [30, 45, 60, 75, 90, 125, 160],
      noiseLevelDb: {
        min: 19,
        max: 50,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      features:
        "Встроенный датчик СО2. Интегрируются в систему «умного дома» Smart Life",
      filterClasses: ["G4", "E11"],
      hiddenWiring: true,
      speeds: 7,
      warrantyDeviceYears: 2,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик",
      weightKg: 7,
      nightMode: true,
      airflowMaxM3h: 160,
      roomAreaMaxM2: 50,
      roomAreaRecM2: 40,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1200,
      fanPowerW: 60,
      energyYearWarmKwh: 525,
      energyYearColdKwh: 5300,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 132,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение TION Smart"],
      controlOnDevice: true,
      wifi: true,
      remoteControl: true,
      clusterControl: false,
      recirculation: true,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: true,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "E11",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: false,
      placement: "Внутреннее",
      outdoorTempRange: "−40..+50",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-4s-base/
  {
    id: "brizer-tion-4s-base",
    modelNameEn: "Tion 4S Base",
    modelNameRu: "Тион 4С Бэйс",
    inStock: true,
    price: "76 000 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/53/19/1953/images/5216/5216.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/53/19/1953/images/5216/5216.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Base", "Family", "Magic"],
      dimensionsMm: "453х527х203",
      airflowM3h: [140],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      filterClasses: ["G4", "H13"],
      hiddenWiring: true,
      speeds: 6,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик + Вспененный полиэтилен",
      nightMode: true,
      airflowMaxM3h: 140,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 25,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1450,
      fanPowerW: 30,
      energyYearWarmKwh: 262,
      energyYearColdKwh: 1700,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение для смартфона"],
      controlOnDevice: false,
      recirculation: true,
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: false,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "H13 (опция)",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: true,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "-40..+50°",
      indoorTempRange: "+5°..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-4s-family/
  {
    id: "brizer-tion-4s-family",
    modelNameEn: "Tion 4S Family",
    modelNameRu: "Тион 4С Фэмили",
    inStock: true,
    price: "77 199 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/54/19/1954/images/5217/5217.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/54/19/1954/images/5217/5217.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Base", "Family", "Plus", "Magic"],
      dimensionsMm: "453х527х203",
      airflowM3h: [140],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      features: "В комплекте поставки включен фильтр H13",
      filterClasses: ["G4", "H13"],
      hiddenWiring: true,
      speeds: 6,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик + Вспененный полиэтилен",
      nightMode: true,
      airflowMaxM3h: 140,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 25,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1450,
      fanPowerW: 30,
      energyYearWarmKwh: 262,
      energyYearColdKwh: 1700,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение для смартфона"],
      controlOnDevice: false,
      recirculation: true,
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: false,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "H13",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: true,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "-40..+50°",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-tion-4s-plus/
  {
    id: "brizer-tion-tion-4s-plus",
    modelNameEn: "Tion 4S Plus",
    modelNameRu: "Тион 4С Плюс",
    inStock: true,
    price: "96 000 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/26/20/2026/images/5487/5487.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/26/20/2026/images/5487/5487.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Base", "Family", "Plus", "Magic"],
      airflowM3h: [140],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      filterClasses: ["G4", "H13"],
      hiddenWiring: true,
      speeds: 6,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик + Вспененный полиэтилен",
      nightMode: true,
      airflowMaxM3h: 140,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 25,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1450,
      fanPowerW: 30,
      energyYearWarmKwh: 262,
      energyYearColdKwh: 1700,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение для смартфона"],
      controlOnDevice: false,
      recirculation: true,
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: false,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "H13",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: true,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "-40..+50°",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-tion-4s-magic/
  {
    id: "brizer-tion-4s-magic",
    modelNameEn: "Tion 4S Magic",
    modelNameRu: "Тион 4С Мэджик",
    inStock: true,
    price: "97 200 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/55/19/1955/images/5218/5218.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/55/19/1955/images/5218/5218.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Base", "Family", "Magic"],
      dimensionsMm: "453х527х203",
      airflowM3h: [140],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток", "Рециркуляция", "Смешанный режим"],
      features: "В комплект поставки включена базовая станция Magic Air",
      filterClasses: ["G4", "H13"],
      hiddenWiring: true,
      speeds: 6,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 45,
      bodyMaterial: "Пластик + Вспененный полиэтилен",
      nightMode: true,
      airflowMaxM3h: 140,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 25,
      personsMax: 5,
      personsRec: 3,
      heater: true,
      heaterPowerW: 1450,
      fanPowerW: 30,
      energyYearWarmKwh: 262,
      energyYearColdKwh: 1700,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["Пульт ДУ", "приложение для смартфона"],
      controlOnDevice: false,
      recirculation: true,
      syncDevices: true,
      heaterOffOption: true,
      schedule: true,
      sensors: {
        co2: true,
        co: false,
        airQuality: false,
        humidity: true,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G4",
      filterClassMax: "H13",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: true,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "-40..+50°",
      indoorTempRange: "+5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/tion-o2-base/
  {
    id: "tion-o2-base",
    modelNameEn: "TION O2 Base",
    inStock: true,
    price: "46 499 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/75/07/775/images/673/673.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/75/07/775/images/673/673.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Бризер",
      dimensionsMm: "514 × 454 × 163",
      airflowM3h: [120],
      noiseLevelDb: {
        min: 32,
      },
      modes: ["Приток, Клапан"],
      features: "В поставке отсутствует ХЕПА и угольный фильтр.",
      filterClasses: ["G3-H11"],
      hiddenWiring: false,
      speeds: 3,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 45,
      bodyMaterial: "белый пластик",
      nightMode: true,
      airflowMaxM3h: 120,
      roomAreaMaxM2: 40,
      personsMax: 4,
      fanPowerW: 50,
      wallThicknessMm: "от 10 мм",
      ductDiameterMm: 100,
      remoteControl: true,
      syncDevices: false,
      heaterOffOption: true,
      schedule: false,
      sensors: {
        co2: false,
        airQuality: false,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: false,
      condensateProtection: false,
      freezeProtection: false,
      filterClassMin: "G3",
      filterClassMax: "H11 (приобретается дополнительно)",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: false,
      placement: "Внутри помещения",
      outdoorTempRange: "-40..+45",
      indoorTempRange: "-40..+45",
      maxHumidity: 60,
      powerSupply: "220\\50",
      voltage: 220,
      powerCableLengthM: 4,
      productionCountry: "Россия (сборка - Китай)",
      mountingHoleMm: 112,
      heater: false,
    },
  },

  // https://fresh-air.moscow/product/tion-o2-standart/
  {
    id: "tion-o2-standart",
    modelNameEn: "Tion O2 Standart",
    modelNameRu: "Тион О2 Стандарт",
    inStock: true,
    price: "50 100 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/77/07/777/images/797/797.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/77/07/777/images/797/797.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["Lite", "base", "standart", "mac", "top"],
      dimensionsMm: "514 × 454 × 163",
      airflowM3h: [120],
      noiseLevelDb: {
        min: 32,
      },
      modes: ["Приток, пассивный клапан"],
      filterClasses: ["G3", "G4 + H11 + адсорбционно-каталитический"],
      hiddenWiring: false,
      speeds: 4,
      warrantyDeviceYears: 1,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик",
      weightKg: 8.5,
      nightMode: true,
      airflowMaxM3h: 120,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 20,
      personsMax: 4,
      heater: true,
      heaterPowerW: 1450,
      fanPowerW: 18,
      energyYearWarmKwh: 200,
      energyYearColdKwh: 1700,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["Электронный на корпусе + ПДУ"],
      controlOnDevice: true,
      wifi: false,
      remoteControl: true,
      recirculation: false,
      mixing: false,
      valve: true,
      display: "Да",
      syncDevices: false,
      heaterOffOption: true,
      schedule: false,
      sensors: {
        co2: false,
        co: false,
        airQuality: false,
        humidity: false,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G3",
      filterClassMax: "H11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: true,
      placement: "Внутри помещения",
      outdoorTempRange: "-40..+45",
      indoorTempRange: "5..+50",
      maxHumidity: 80,
      powerSupply: "220/50",
      voltage: 220,
      powerCableLengthM: 4,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/tion-mac/
  {
    id: "tion-mac",
    modelNameEn: "Tion O2 MAC",
    modelNameRu: "Тион О2 МАK",
    inStock: true,
    price: "54 150 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/54/09/954/images/1344/1344.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/54/09/954/images/1344/1344.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      type: "Бризер",
      modifications: ["Standart"],
      dimensionsMm: "514х454х163",
      airflowM3h: [130],
      noiseLevelDb: {
        min: 32,
      },
      modes: ["Приток + клапан"],
      features: "Подаёт воздух вверх под углом 30 градусов",
      filterClasses: ["F7 + H11 + адсорбционно-каталитический"],
      hiddenWiring: true,
      speeds: 4,
      warrantyDeviceYears: 12,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 50,
      bodyMaterial: "АВС пластик",
      weightKg: 8.5,
      nightMode: false,
      airflowMaxM3h: 130,
      roomAreaMaxM2: 40,
      personsMax: 4,
      heater: true,
      heaterPowerW: 1000,
      fanPowerW: 50,
      wallThicknessMm: "от 10 мм",
      ductDiameterMm: 100,
      controlOnDevice: true,
      remoteControl: true,
      heaterOffOption: true,
      schedule: false,
      climateControl: true,
      filterReplacementIndicator: true,
      timer: false,
      condensateProtection: false,
      freezeProtection: false,
      filterClassMax: "H11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      harmfulGases: true,
      placement: "Внутри помещения",
      outdoorTempRange: "-40..+45",
      maxHumidity: 60,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/tion-mac-magicair/
  {
    id: "tion-mac-magicair",
    inStock: true,
    price: "70 000 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/58/09/958/images/1863/1863.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/58/09/958/images/1863/1863.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      dimensionsMm: "514 × 454 × 163",
      airflowM3h: [120],
      noiseLevelDb: {
        min: 32,
      },
      filterClasses: ["F7 + H11 + адсорбционно-каталитический"],
      hiddenWiring: false,
      warrantyInstallYears: 5,
      bodyMaterial: "белый пластик",
      weightKg: 8.5,
      nightMode: false,
      airflowMaxM3h: 120,
      roomAreaMaxM2: 40,
      personsMax: 4,
      heater: true,
      fanPowerW: 50,
      wallThicknessMm: "от 10 мм",
      ductDiameterMm: 100,
      remoteControl: true,
      heaterOffOption: true,
      schedule: false,
      climateControl: true,
      filterReplacementIndicator: true,
      timer: false,
      condensateProtection: false,
      freezeProtection: false,
      filterClassMax: "H11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      harmfulGases: true,
      placement: "Внутри помещения",
      outdoorTempRange: "-40..+45",
      maxHumidity: 60,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/tion-mini/
  {
    id: "tion-mini",
    modelNameEn: "Tion Breezer Lite",
    modelNameRu: "Тион Бризер Лайт",
    inStock: true,
    price: "38 199 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/02/webp/04/11/1104/images/1991/1991.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/02/webp/04/11/1104/images/1991/1991.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Tion",
      view: "Проветриватель",
      type: "Бризер",
      modifications: ["ECO"],
      dimensionsMm: "260х260х130",
      airflowM3h: [100],
      noiseLevelDb: {
        min: 18,
      },
      modes: ["Приток, пассивный клапан"],
      filterClasses: ["G3-H11"],
      hiddenWiring: true,
      speeds: 6,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик",
      weightKg: 3.5,
      nightMode: true,
      airflowMaxM3h: 100,
      roomAreaMaxM2: 23,
      roomAreaRecM2: 15,
      personsMax: 3,
      personsRec: 2,
      heater: true,
      heaterPowerW: 900,
      fanPowerW: 25,
      energyYearWarmKwh: 219,
      energyYearColdKwh: 1450,
      wallThicknessMm: "250...3000",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["С телефона\\планшета"],
      controlOnDevice: true,
      wifi: true,
      remoteControl: false,
      recirculation: false,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      heaterOffOption: true,
      schedule: false,
      sensors: {
        co2: false,
        co: false,
        airQuality: false,
        humidity: false,
      },
      climateControl: false,
      filterReplacementIndicator: true,
      timer: false,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G3",
      filterClassMax: "H11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: true,
      placement: "Внутреннее",
      outdoorTempRange: "−25°..+50°",
      indoorTempRange: "+5°..+50",
      maxHumidity: 80,
      powerSupply: "220\\50",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/brizer-ballu-oneair-asp-100/
  {
    id: "brizer-ballu-oneair-asp-100",
    modelNameEn: "Ballu ONEAIR ASP-100",
    modelNameRu: "Баллу ОНЭИР АСП-100",
    inStock: true,
    price: "33 490 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/62/26/2662/images/8554/8554.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/62/26/2662/images/8554/8554.750x350.webp",
    ],
    specs: {
      brand: "Ballu",
      view: "Бризер",
      modifications: ["Белый или серый цвет"],
      dimensionsMm: "264х352х160",
      airflowM3h: [120],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток, клапан, рециркулятор"],
      features: "Поток воздуха направлен вверх",
      filterClasses: ["Префильтр", "H13"],
      hiddenWiring: true,
      speeds: 8,
      warrantyDeviceYears: 2,
      warrantyInstallYears: 5,
      bodyMaterial: "ABS-Пластик",
      weightKg: 3.5,
      nightMode: false,
      airflowMaxM3h: 120,
      roomAreaMaxM2: 30,
      roomAreaRecM2: 15,
      personsMax: 4,
      personsRec: 2,
      heater: true,
      heaterPowerW: 1000,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 132,
      ductDiameterMm: 100,
      control: ["Моб. приложение"],
      controlOnDevice: true,
      wifi: true,
      remoteControl: false,
      clusterControl: false,
      recirculation: false,
      mixing: false,
      valve: true,
      display: "На экране телефона/планшета",
      syncDevices: true,
      schedule: true,
      sensors: {
        co2: false,
        co: false,
        airQuality: true,
        humidity: false,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: false,
      filterClassMax: "H13",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      harmfulGases: false,
      placement: "Внутреннее",
      outdoorTempRange: "-30..+50",
      powerSupply: "220-240/50-60",
      powerCableLengthM: 2,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/ballu-oneair-home-pro-asp-200/
  {
    id: "ballu-oneair-home-pro-asp-200",
    modelNameEn: "Ballu ONEAiR Home Pro ASP-200",
    modelNameRu: "Баллу УАНЭиР Хом Про АСП-200",
    inStock: true,
    price: "53 990 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/41/17/1741/images/4721/4721.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/41/17/1741/images/4721/4721.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Ballu",
      view: "Бризер",
      dimensionsMm: "575х445х190",
      airflowM3h: [200],
      noiseLevelDb: {
        min: 19,
      },
      modes: ["Приток, клапан, рециркулятор"],
      features: "Поток воздуха направлен вниз",
      filterClasses: ["F5/H11/Угольный фильтр"],
      hiddenWiring: true,
      speeds: 9,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      bodyMaterial: "Пластик",
      weightKg: 7.2,
      nightMode: true,
      airflowMaxM3h: 200,
      roomAreaMaxM2: 75,
      roomAreaRecM2: 72,
      heaterPowerW: 1200,
      wallThicknessMm: "10...3000",
      mountingHoleMm: 140,
      ductDiameterMm: 125,
      control: ["Пульт ДУ/ Моб. приложение"],
      controlOnDevice: true,
      wifi: true,
      remoteControl: true,
      recirculation: true,
      mixing: false,
      valve: true,
      display: "Да",
      syncDevices: true,
      schedule: true,
      sensors: {
        co2: false,
        co: false,
        airQuality: true,
        humidity: false,
      },
      climateControl: true,
      filterReplacementIndicator: true,
      timer: true,
      filterClassMin: "G2",
      filterClassMax: "H11",
      carbonFilter: true,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      placement: "Внутреннее",
      outdoorTempRange: "-40..+50",
      powerSupply: "220-240/50-60",
      voltage: 220,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/ballu-oneair-compact-asp-80/
  {
    id: "ballu-oneair-compact-asp-80",
    modelNameEn: "Ballu ONEAiR Compact ASP-80",
    modelNameRu: "Баллу УАНЭиР Компакт АСП-80",
    inStock: true,
    price: "18 990 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/40/17/1740/images/4711/4711.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/04/webp/40/17/1740/images/4711/4711.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Ballu",
      view: "Бризер",
      dimensionsMm: "358х262х140",
      airflowM3h: [],
      noiseLevelDb: {
        min: 24,
      },
      modes: ["Приток, клапан, рециркулятор"],
      features:
        "По факту это сертифицированный в России  XIAOMI BioFamily Wall Fresh Air Blower N80",
      filterClasses: ["G3", "G4", "M5", "F7", "H13"],
      hiddenWiring: true,
      speeds: 3,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 40,
      bodyMaterial: "Пластик",
      weightKg: 3.8,
      nightMode: true,
      airflowMaxM3h: 80,
      roomAreaMaxM2: 15,
      roomAreaRecM2: 27,
      personsMax: 4,
      personsRec: 2,
      heater: true,
      heaterPowerW: 600,
      fanPowerW: 15,
      energyYearWarmKwh: 131,
      energyYearColdKwh: 2800,
      wallThicknessMm: "10",
      mountingHoleMm: 112,
      ductDiameterMm: 100,
      control: ["На панели прибора/ДУ"],
      controlOnDevice: true,
      wifi: false,
      remoteControl: false,
      clusterControl: false,
      recirculation: true,
      mixing: false,
      valve: false,
      display: "Нет",
      syncDevices: false,
      heaterOffOption: true,
      schedule: false,
      sensors: {
        co2: false,
        co: false,
        airQuality: false,
        humidity: false,
      },
      climateControl: true,
      filterReplacementIndicator: false,
      timer: false,
      condensateProtection: true,
      freezeProtection: true,
      filterClassMin: "G3",
      filterClassMax: "H13",
      carbonFilter: false,
      allergens: true,
      pollen: true,
      dust: true,
      microorganisms: true,
      photocatFilter: false,
      microorganismNeutralization: false,
      harmfulGases: false,
      placement: "Внутреннее",
      outdoorTempRange: "-25..+50",
      indoorTempRange: "+50",
      maxHumidity: 80,
      powerSupply: "220-240/50-60",
      voltage: 220,
      powerCableLengthM: 3,
      recuperation: false,
      productionCountry: "Китай",
    },
  },

  // https://fresh-air.moscow/product/pritochnaya-ustanovka-royal-clima-brezza-rcb-150-lux/
  {
    id: "pritochnaya-ustanovka-royal-clima-brezza-rcb-150-lux",
    modelNameEn: "Royal Clima BREZZA RCB 150 LUX",
    modelNameRu: "Роял Клима Брезза RCB 150 LUX",
    inStock: true,
    price: "52 000 руб.",
    images: [
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/45/20/2045/images/5557/5557.750x0.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/00/webp/45/20/2045/images/5557/5557.750x350.webp",
      "https://fresh-air.moscow/wa-data/public/shop/products/14/webp/data/public/site/img/Reshetki/Colors.webp",
    ],
    specs: {
      brand: "Royal Clima",
      view: "Приточная установка",
      type: "Аэрогивер",
      dimensionsMm: "620х400х135",
      airflowM3h: [150],
      noiseLevelDb: {
        min: 20,
      },
      modes: [
        "Приточный, интеллектуальный,защита от конденсации, режим рециркуляции, ECO режим, ночной режим",
      ],
      filterClasses: ["5 - ступенчатая фильтрация"],
      hiddenWiring: true,
      speeds: 3,
      warrantyDeviceYears: 24,
      warrantyInstallYears: 5,
      noiseSuppressionDb: 40,
      bodyMaterial: "Пластик",
      weightKg: 6.7,
      nightMode: true,
      airflowMaxM3h: 150,
      roomAreaMaxM2: 40,
      roomAreaRecM2: 20,
      wifi: false,
      remoteControl: false,
      recirculation: true,
      display: "На пульте ДУ",
      schedule: true,
      condensateProtection: true,
      freezeProtection: true,
      indoorTempRange: "от 0 ~ +50",
      powerSupply: "230 +-10%",
      voltage: 220,
      productionCountry: "Китай",
    },
  },
];

export const mockProductsShort: ProductShort[] = mockProducts.map(
  (product) => ({
    id: product.id,
    modelNameEn: product.modelNameEn,
    modelNameRu: product.modelNameRu,
    inStock: product.inStock,
    price: product.price,
    images: product.images,
  })
);
